---
- hosts: ios
  vars:
   ansible_connection: ansible.netcommon.network_cli
   ansible_network_os: cisco.ios.ios
  tasks:
  - name: Merge interface configuration
    cisco.ios.ios_interfaces:
      config:
        - name: GigabitEthernet0/2
          description: Configured by Ansible
          enabled: true
      state: merged
    register: result
